### ISSUE TITLE
componentes funcionales

### ISSUE THREAD

**Issue by markozxuu** [lessly-zuniga/portfolio#1]
Hola Lessly 👋😄 

Acabo de revisar tu app por curiosidad y me percate de algunas cosas que podrías mejorar hablando específicamente de código. Note que en ningún componente estas usando el `state` de React por lo que creo que no es necesario que escribas tus componente con sintaxis de clase `ES6`

Un pequeño ejemplo de como podrías mejorarlo:

![carbon](https://user-images.githubusercontent.com/16585386/67999761-181b2d80-fc23-11e9-82bf-6a21ae939249.png)

Escribir tus componente a funciones tienen grandes ventajas, que son las siguientes:

- no tienes que pensar en el uso del `this`, todo el léxico esta en scope de la función
- más amigable al momento de que pase por la transpilación. Esto lo digo porque a `babelJs` se le da mejor transpilar funciones en lugar de clases, el gasto de computo es mucho menor

**Comment by lessly-zuniga** [comment]
Hola!  😄

Muchas gracias por tu comentario, me fue muy útil y  ya lo resolví .
